-- Customer reviews submitted by authenticated customers.
create table if not exists public.customer_reviews (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	customer_name text not null,
	review text not null check (char_length(review) between 1 and 2000),
	rating smallint not null check (rating between 1 and 5),
	approved boolean not null default false,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

alter table public.customer_reviews enable row level security;

drop policy if exists "Anyone can read approved reviews" on public.customer_reviews;
create policy "Anyone can read approved reviews"
	on public.customer_reviews
	for select
	using (approved = true);

drop policy if exists "Customers can submit their own reviews" on public.customer_reviews;
create policy "Customers can submit their own reviews"
	on public.customer_reviews
	for insert
	to authenticated
	with check (user_id = auth.uid() and approved = false);

drop policy if exists "Customers can update their own reviews" on public.customer_reviews;
create policy "Customers can update their own reviews"
	on public.customer_reviews
	for update
	to authenticated
	using (user_id = auth.uid() and approved = false)
	with check (user_id = auth.uid() and approved = false);

create index if not exists customer_reviews_approved_created_at_idx
	on public.customer_reviews (approved, created_at desc);
